name: face-recognition-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - dlib
  - face_recognition
  - numpy
  - streamlit
  - pip:
    - opencv-python-headless
    - streamlit-webrtc
